services:
  image_test:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    network_mode: host
    privileged: true
    container_name: ignition-bridge
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=":0",
      - XAUTHORITY="/run/user/1000/.mutter-Xwaylandauth.PCMQQ1",
      - QT_X11_NO_MITSHM= 1
